### ISSUE TITLE
Modify Centinel of YAML to avoid Templater Notice

### ISSUE THREAD

**Issue by brimwats** [RafaelGB/obsidian-db-folder#179]
Hello

When I try to make a DB Folder and do anything with it, i get in the range of 150 errors. Here's how you reproduce.

Make a DB Folder from this zip file. There is a folder note named `1. Classifcation`. DB Folder will error out, and create "untitled database". Rename it 1. Classification Database.

[1. Classification.zip](https://github.com/RafaelGB/obsidian-db-folder/files/9031426/1.Classification.zip)

Enable "created date" column. Notice that a created date column is not added. Create a new column. Name it `Created:`

You will get several errors about nested YAML. This is because notes have a "created" field already but it is not being added.

Here are all of the errors:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at eval (plugin:obsidian-collapse-all-plugin:367:46)
    at Array.every (<anonymous>)
    at TagPaneProvider.tagsAreCollapsed (plugin:obsidian-collapse-all-plugin:367:22)
    at TagPaneProvider.allCollapsed (plugin:obsidian-collapse-all-plugin:355:21)
    at TagPaneProvider.updateButtonIcon (plugin:obsidian-collapse-all-plugin:208:39)
    at eval (plugin:obsidian-collapse-all-plugin:173:18)
    at Array.forEach (<anonymous>)
    at TagPaneProvider.updateButtonIcons (plugin:obsidian-collapse-all-plugin:172:21)
    at eval (plugin:obsidian-collapse-all-plugin:485:34)
    at Array.forEach (<anonymous>)
plugin:metaedit:5266 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at OnFileModifyAutomatorManager.onFileModify (plugin:metaedit:5266:29)
plugin:obsidian-banners:13 Uncaught (in promise) TypeError: Cannot destructure property 'frontmatter' of 'this.metadata.getFileCache(...)' as it is null.
    at Ne.getBannerDataFromFile (plugin:obsidian-banners:13:831)
    at Mu.lintBannerSource (plugin:obsidian-banners:28:11227)
    at eval (plugin:obsidian-banners:28:9340)
    at t.e.tryTrigger (app://obsidian.md/app.js:1:964139)
    at t.e.trigger (app://obsidian.md/app.js:1:964072)
    at t.trigger (app://obsidian.md/app.js:1:1514235)
    at t.activeLeafEvents (app://obsidian.md/app.js:1:1504934)
    at a (app://obsidian.md/app.js:1:264389)
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at eval (plugin:obsidian-collapse-all-plugin:367:46)
    at Array.every (<anonymous>)
    at TagPaneProvider.tagsAreCollapsed (plugin:obsidian-collapse-all-plugin:367:22)
    at TagPaneProvider.allCollapsed (plugin:obsidian-collapse-all-plugin:355:21)
    at TagPaneProvider.updateButtonIcon (plugin:obsidian-collapse-all-plugin:208:39)
    at eval (plugin:obsidian-collapse-all-plugin:173:18)
    at Array.forEach (<anonymous>)
    at TagPaneProvider.updateButtonIcons (plugin:obsidian-collapse-all-plugin:172:21)
    at eval (plugin:obsidian-collapse-all-plugin:485:34)
    at Array.forEach (<anonymous>)
plugin:metaedit:5266 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at OnFileModifyAutomatorManager.onFileModify (plugin:metaedit:5266:29)
plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 Bad template syntax

Unexpected token '%'
====================
var tR='',__l,__lP,include=E.include.bind(E),includeFile=E.includeFile.bind(E)
function layout(p,d){__l=p;__lP=d}
const _prs = [];
tR+='---\n\ndatabase-plugin: basic\n\n---\n\n'
_prs.push(%
name: new database
description: new description
columns:
  column1:
    input: text
    key: column1
    accessor: column1
    label: Column 1
    position: 0
    skipPersist: false
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
config:
  enable_show_state: false
  group_folder_column: 
  remove_field_when_delete_column: false
  cell_size: normal
  sticky_first_column: false
  show_metadata_created: false
  show_metadata_modified: false
  source_data: current_folder
  source_form_result: root
  show_metadata_tasks: false
  frontmatter_quote_wrap: false
  row_templates_folder: /
  current_row_template: 
filters:
%);
tR+='rJ2KqXzxQg'
const _rst = await Promise.all(_prs);
tR = tR.replace(/rJ2KqXzxQg/g, () => _rst.shift());
if(__l)tR=await includeFile(__l,Object.assign(tp,{body:tR},__lP))
if(cb){cb(null,tR)} return tR

log_error @ plugin:templater-obsidian:82
2app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at eval (plugin:obsidian-collapse-all-plugin:367:46)
    at Array.every (<anonymous>)
    at TagPaneProvider.tagsAreCollapsed (plugin:obsidian-collapse-all-plugin:367:22)
    at TagPaneProvider.allCollapsed (plugin:obsidian-collapse-all-plugin:355:21)
    at TagPaneProvider.updateButtonIcon (plugin:obsidian-collapse-all-plugin:208:39)
    at eval (plugin:obsidian-collapse-all-plugin:173:18)
    at Array.forEach (<anonymous>)
    at TagPaneProvider.updateButtonIcons (plugin:obsidian-collapse-all-plugin:172:21)
    at eval (plugin:obsidian-collapse-all-plugin:485:34)
    at Array.forEach (<anonymous>)
react-beautiful-dnd.esm.js:39 react-beautiful-dndA setup problem was encountered.> Invariant failed: Draggable[id: column1]: Unable to find drag handle👷‍ This is a development only message. It will be removed in production builds.
log @ react-beautiful-dnd.esm.js:39
react-beautiful-dnd.esm.js:39 react-beautiful-dndA setup problem was encountered.> Invariant failed: Draggable[id: __file__]: Unable to find drag handle👷‍ This is a development only message. It will be removed in production builds.
log @ react-beautiful-dnd.esm.js:39
react-beautiful-dnd.esm.js:39 react-beautiful-dndA setup problem was encountered.> Invariant failed: Draggable[id: column1]: Unable to find drag handle👷‍ This is a development only message. It will be removed in production builds.
log @ react-beautiful-dnd.esm.js:39
react-beautiful-dnd.esm.js:39 react-beautiful-dndA setup problem was encountered.> Invariant failed: Draggable[id: __file__]: Unable to find drag handle👷‍ This is a development only message. It will be removed in production builds.
log @ react-beautiful-dnd.esm.js:39
9app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at eval (plugin:obsidian-collapse-all-plugin:367:46)
    at Array.every (<anonymous>)
    at TagPaneProvider.tagsAreCollapsed (plugin:obsidian-collapse-all-plugin:367:22)
    at TagPaneProvider.allCollapsed (plugin:obsidian-collapse-all-plugin:355:21)
    at TagPaneProvider.updateButtonIcon (plugin:obsidian-collapse-all-plugin:208:39)
    at eval (plugin:obsidian-collapse-all-plugin:173:18)
    at Array.forEach (<anonymous>)
    at TagPaneProvider.updateButtonIcons (plugin:obsidian-collapse-all-plugin:172:21)
    at eval (plugin:obsidian-collapse-all-plugin:485:34)
    at Array.forEach (<anonymous>)
app.js:1 TypeError: t.view.revealInFolder is not a function
    at e.revealInFolder (app://obsidian.md/app.js:1:1728486)
    at eval (plugin:alx-folder-note:46:14219)
    at e.l [as revealInFolder] (plugin:alx-folder-note:46:1379)
    at Object.checkCallback (app://obsidian.md/app.js:1:1727019)
    at fH (app://obsidian.md/app.js:1:1668261)
    at e.executeCommand (app://obsidian.md/app.js:1:1669608)
    at e.executeCommandById (app://obsidian.md/app.js:1:1669515)
    at eval (plugin:key-promoter:280:63)
    at e.check (plugin:key-promoter:176:53)
    at e.wrapper (plugin:key-promoter:155:24)
e.executeCommand @ app.js:1
4app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at eval (plugin:obsidian-collapse-all-plugin:367:46)
    at Array.every (<anonymous>)
    at TagPaneProvider.tagsAreCollapsed (plugin:obsidian-collapse-all-plugin:367:22)
    at TagPaneProvider.allCollapsed (plugin:obsidian-collapse-all-plugin:355:21)
    at TagPaneProvider.updateButtonIcon (plugin:obsidian-collapse-all-plugin:208:39)
    at eval (plugin:obsidian-collapse-all-plugin:173:18)
    at Array.forEach (<anonymous>)
    at TagPaneProvider.updateButtonIcons (plugin:obsidian-collapse-all-plugin:172:21)
    at eval (plugin:obsidian-collapse-all-plugin:485:34)
    at Array.forEach (<anonymous>)
ErrorComponents.tsx:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at generateErrorComponent (plugin:dbfolder:56355:22)
    at DbFolderError.render (plugin:dbfolder:56381:32)
    at DatabaseView.eval (plugin:dbfolder:133181:23)
    at Generator.throw (<anonymous>)
    at rejected (plugin:dbfolder:39:65)
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at eval (tag-pane.ts:47:42)
    at Array.every (<anonymous>)
    at TagPaneProvider.tagsAreCollapsed (tag-pane.ts:47:18)
    at TagPaneProvider.allCollapsed (tag-pane.ts:33:17)
    at TagPaneProvider.updateButtonIcon (base.ts:236:33)
    at eval (base.ts:191:12)
    at Array.forEach (<anonymous>)
    at TagPaneProvider.updateButtonIcons (base.ts:190:17)
    at eval (plugin.ts:56:22)
    at Array.forEach (<anonymous>)
```

**Comment by RafaelGB** [comment]
looks like a problem with the yaml that you shared under `filters:`

Have to test it well. Thanks for the report @brimwats

**Comment by brimwats** [comment]
I don't think i have any filters. Or at least I can't find anywhere to set filters

**Comment by RafaelGB** [comment]
If you have activated the Templater option of run qith every new file, the database has the same centinel

<%%
yaml bere
%%>

but should not be problem with that, Templater just ignore that possible script.

Anyway, could be an option to substitute the plugin script in the future, I will add this Fr as visual label to the roadmap

**Comment by brimwats** [comment]
I see, what you're saying is that the templater setting "run at file creation" is what is interfering with the dbfolder working? so I should try it with that switched off?

**Comment by RafaelGB** [comment]
you can leave it enabled, the error message does not affect the behaviour, Templater take the dbfolder yaml as and js code and try to execute it, fails and nothings happend

**Comment by brimwats** [comment]
ah, so I can't fix or use db folder until it is resolved then? (just trying to understand if anything I can do! :) )

**Comment by RafaelGB** [comment]
You can use it completely normally, it doesn't affect the plugin logic at all or at least it shouldn't

**Comment by brimwats** [comment]
well the plugin isn't working? I have the reproduction steps there— the created date doesn't show a created date because my yaml already has a created date. there's an invisible column called column 1 that always shows up, but I don't think it should?

**Comment by RafaelGB** [comment]
Its a default column, you can delete it and add the columns that you want
