### ISSUE TITLE
Filter error - Contain, start, end

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#72]
**Describe the bug**
Filter configuration does not work correctly when you use contain, start or end

**Screenshots**

https://user-images.githubusercontent.com/7627504/170429035-9d295e05-2da9-4e99-ae1f-7818e97df968.mp4

**Desktop (please complete the following information):**
-windows 11
-obsidian 14.13
-1.4.0 version

**Comment by RafaelGB** [comment]
hi @javiavid  thanks for your testing! It will be added as a bug and considered with high priority

**Comment by RafaelGB** [comment]
Starting with this issue

**Comment by RafaelGB** [comment]
the error could not be reproduced. I would need the console logs to get more detail

**Comment by tqiu8** [comment]
Not the OP but hitting the same bugs. This is my console output:
```
[2022-05-30T16:49:18.624Z] [error] initDatabase pages/Projects/Projects.md [TypeError: Cannot read properties of undefined (reading 'includes')
    at DataviewProxy.filter (ev…]0: TypeError: Cannot read properties of undefined (reading 'includes')
    at DataviewProxy.filter (eval at <anonymous> (app://obsidian.md/app.js:1:1511107), <anonymous>:56019:37)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1511107), <anonymous>:56372:66)
    at Array.filter (<anonymous>)
    at Proxy.where (eval at <anonymous> (app://obsidian.md/app.js:1:1511107), <anonymous>:11732:39)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1511107), <anonymous>:56372:39)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1511107), <anonymous>:26:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app://obsidian.md/app.js:1:1511107), <anonymous>:22:12)
    at adapterTFilesToRows (eval at <anonymous> (app://obsidian.md/app.js:1:1511107), <anonymous>:56364:12)length: 1[[Prototype]]: Array(0)
VM3836:56019 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at DataviewProxy.filter (eval at <anonymous> (app.js:1:1511107), <anonymous>:56019:37)
    at eval (eval at <anonymous> (app.js:1:1511107), <anonymous>:56372:66)
    at Array.filter (<anonymous>)
    at Proxy.where (eval at <anonymous> (app.js:1:1511107), <anonymous>:11732:39)
    at eval (eval at <anonymous> (app.js:1:1511107), <anonymous>:56372:39)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1511107), <anonymous>:26:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1:1511107), <anonymous>:22:12)
    at adapterTFilesToRows (eval at <anonymous> (app.js:1:1511107), <anonymous>:56364:12)
```

**Comment by RafaelGB** [comment]
I Think is than simple as control c.field exist first =P. I will generate a version now, so I will include this changes too!
```typescript
case OperatorFilter.CONTAINS:
                    if (p[c.field] !== undefined && !p[c.field].includes(c.value)) return false;
                    break;
                case OperatorFilter.STARTS_WITH:
                    if (p[c.field] !== undefined && !p[c.field].startsWith(c.value)) return false;
                    break;
                case OperatorFilter.ENDS_WITH:
                    if (p[c.field] !== undefined && !p[c.field].endsWith(c.value)) return false;
                    break;
```

**Comment by tqiu8** [comment]
@RafaelGB Thank you so much!

**Comment by RafaelGB** [comment]
So is it fixed ?

**Comment by javiavid** [comment]
Yes, for me is correct
