### ISSUE TITLE
[Bug]:  Inconsistent Recognition of Non-Hyphenated Inline Fields

### ISSUE THREAD

**Issue by Bluemoondragon07** [RafaelGB/obsidian-db-folder#800]
### What happened?

So, in various notes, I have this inline field:
```
[Scientific Name:: ]
```
In the database view of that group of notes, when I try to add this column, it gives me two options: `scientific-name` and `Scientific Name`.  

When I choose `Scientific Name`, nothing shows up in that column; but when I choose `scientific-name` it shows all of my data. If I go into a note and type in something like, `[Scientific Name:: Canis lupis]`, then `Canis lupis` shows up in the `scientific-name` column instead of the `Scientific Name` column.

But, when I type something into the `scientific-name` column, it creates a new field in the note, `scientific-name:: whatever I typed`, instead of putting it in the `Scientific Name` field, which I thought it was registering as `scientific-name`. And strangely, it always leaves out the closing bracket at the end.

Now, if I go back to the table and type `Canis lupis` into the `Scientific Name` column instead, it will again create a new field in the note: `[Scientific_Name:: Canis lupis`. And again, it leaves out the closing bracket.

The fields were purely inline as well and  weren't contained in callouts or blockquotes.

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at eval (plugin:dbfolder:118:6542)
    at a (plugin:dbfolder:109:304393)
    at h0.eval (plugin:dbfolder:118:6449)
    at Generator.next (<anonymous>)
    at o (plugin:dbfolder:1:748)
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'top')
    at t.coordsAtPos (app.js:1:1316723)
    at t.updatePosition (app.js:1:1666908)
    at t.showSuggestions (app.js:1:1666606)
    at t.showSuggestions (app.js:1:1668824)
    at t.<anonymous> (app.js:1:1666389)
    at app.js:1:235505
    at Object.next (app.js:1:235610)
    at a (app.js:1:234349)
2plugin:dbfolder:118 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'tags')
    at X0.checkIfFileIsInSource (plugin:dbfolder:118:26887)
    at X0.eval (plugin:dbfolder:118:25714)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
    at new Promise (<anonymous>)
    at a (plugin:dbfolder:1:697)
    at Object.n.actions.dataviewUpdater (plugin:dbfolder:118:25644)
    at eval (plugin:dbfolder:109:249809)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
We have to check the class with the inline builder then

https://github.com/RafaelGB/obsidian-db-folder/blob/master/src/patterns/builders/NoteContentActionBuilder.ts

Thanks for the report!

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/798 fixed with this other one
