### ISSUE TITLE
[Bug]: Error creating new db table

### ISSUE THREAD

**Issue by HynDuf** [RafaelGB/obsidian-db-folder#829]
### Contact Details

chauhuynhnoc@gmail.com

### What happened?

When I create a new simple database table (just "Current folder" option), the bug happened. There is still the db table file created but it is blank. 

I turned off all other plugins (beside Dataview and DB Folder) but the bug still happened. It works in a newly created vault, though.

### What platform were you using?

Desktop

### Version of the plugin

3.3.1

### Relevant log output

```shell
Dataview: version 0.5.55 (requires obsidian 0.13.11)
plugin:dataview:12571 Dataview: all 135 files have been indexed in 0.554s (135 cached, 0 skipped).
plugin:dbfolder:120 Uncaught (in promise) TypeError: X.error is not a function
    at w2.eval (plugin:dbfolder:120:70212)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
    at new Promise (<anonymous>)
    at a (plugin:dbfolder:1:697)
    at w2.initDatabase (plugin:dbfolder:120:69500)
    at w2.eval (plugin:dbfolder:120:69460)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
    at new Promise (<anonymous>)
eval @ plugin:dbfolder:120
eval @ plugin:dbfolder:1
a @ plugin:dbfolder:1
initDatabase @ plugin:dbfolder:120
eval @ plugin:dbfolder:120
eval @ plugin:dbfolder:1
a @ plugin:dbfolder:1
build @ plugin:dbfolder:120
registerView @ plugin:dbfolder:120
D2 @ plugin:dbfolder:120
addView @ plugin:dbfolder:120
setViewData @ plugin:dbfolder:120
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ plugin:dbfolder:1
eval @ plugin:dbfolder:1
a @ plugin:dbfolder:1
build @ plugin:dbfolder:120
registerView @ plugin:dbfolder:120
D2 @ plugin:dbfolder:120
addView @ plugin:dbfolder:120
setViewData @ plugin:dbfolder:120
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.onLoadFile @ app.js:1
eval @ plugin:dbfolder:120
eval @ plugin:dbfolder:1
a @ plugin:dbfolder:1
onLoadFile @ plugin:dbfolder:120
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:dbfolder:120
o @ plugin:dbfolder:120
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.onFileClick @ app.js:1
s @ enhance.js:1
2plugin:dbfolder:120 Uncaught TypeError: X.warn is not a function
    at Object.emit (plugin:dbfolder:120:68820)
    at e.eval (plugin:dbfolder:120:93526)
    at e.o [as executeCommand] (plugin:dbfolder:120:75116)
    at e.onTrigger (app.js:1:1228407)
    at e.handleKey (app.js:1:1035826)
    at e.handleKey (app.js:1:1035939)
    at t.handleKey (app.js:1:1036148)
    at e.onKeyEvent (app.js:1:1037082)
emit @ plugin:dbfolder:120
eval @ plugin:dbfolder:120
o @ plugin:dbfolder:120
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:dbfolder:120 Uncaught (in promise) TypeError: X.info is not a function
    at w2.destroy (plugin:dbfolder:120:70468)
    at w2.eval (plugin:dbfolder:120:72208)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
    at new Promise (<anonymous>)
    at a (plugin:dbfolder:1:697)
    at w2.onClose (plugin:dbfolder:120:72169)
    at w2.<anonymous> (app.js:1:1145526)
    at app.js:1:235505
    at Object.next (app.js:1:235610)
destroy @ plugin:dbfolder:120
eval @ plugin:dbfolder:120
eval @ plugin:dbfolder:1
a @ plugin:dbfolder:1
onClose @ plugin:dbfolder:120
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.close @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.open @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:dbfolder:120
o @ plugin:dbfolder:120
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.onFileClick @ app.js:1
s @ enhance.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.onFileClick @ app.js:1
s @ enhance.js:1
3plugin:dbfolder:120 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'unregisterView')
    at w2.destroy (plugin:dbfolder:120:70358)
    at w2.eval (plugin:dbfolder:120:72208)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
    at new Promise (<anonymous>)
    at a (plugin:dbfolder:1:697)
    at w2.onClose (plugin:dbfolder:120:72169)
    at w2.<anonymous> (app.js:1:1145526)
    at app.js:1:235505
    at Object.next (app.js:1:235610)
destroy @ plugin:dbfolder:120
eval @ plugin:dbfolder:120
eval @ plugin:dbfolder:1
a @ plugin:dbfolder:1
onClose @ plugin:dbfolder:120
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.close @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.open @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:dbfolder:120
o @ plugin:dbfolder:120
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.onFileClick @ app.js:1
s @ enhance.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
t.onFileClick @ app.js:1
s @ enhance.js:1
plugin:dbfolder:120 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'unregisterView')
    at w2.destroy (plugin:dbfolder:120:70358)
    at w2.eval (plugin:dbfolder:120:72208)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
    at new Promise (<anonymous>)
    at a (plugin:dbfolder:1:697)
    at w2.onClose (plugin:dbfolder:120:72169)
    at w2.<anonymous> (app.js:1:1145526)
    at app.js:1:235505
    at Object.next (app.js:1:235610)
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @HynDuf , this is a legacy issue from 3.2.x versions where application traceability was inconsistent. Uninstall the plugin and try installing it again. You can also disable traces in developer options (global plugin options)

**Comment by HynDuf** [comment]
Thanks got it.

**Comment by HynDuf** [comment]
@RafaelGB, after a while I tried installing the plugin again and it's still the issue (even when the logger was turned off).

I looked into the code and see that the `configurerLogger()` was weird.

In the `main.js` of the plugin, it was like this
```js
	configureLogger() {
		this.levelInfo >= q.trace && this.isDebugModeEnabled
			? (this.trace = void 0)
			: (this.trace = () => {}),
			this.levelInfo >= q.debug && this.isDebugModeEnabled
				? (this.debug = void 0)
				: (this.debug = () => {}),
			this.levelInfo >= q.info && this.isDebugModeEnabled
				? (this.info = void 0)
				: (this.info = () => {}),
			this.levelInfo >= q.warn && this.isDebugModeEnabled
				? (this.warn = void 0)
				: (this.warn = () => {}),
			this.levelInfo >= q.error && this.isDebugModeEnabled
				? (this.error = void 0)
				: (this.error = () => {})
	}
```

I should be like this (I copied from the code of the repo)
```js
	configureLogger() {
		this.levelInfo >= q.trace && this.isDebugModeEnabled
			? (this.trace = console.log.bind(console, `[TRACE]`))
			: (this.trace = () => {}),
			this.levelInfo >= q.debug && this.isDebugModeEnabled
				? (this.debug = console.log.bind(console, `[DEBUG]`))
				: (this.debug = () => {}),
			this.levelInfo >= q.info && this.isDebugModeEnabled
				? (this.info = console.log.bind(console, `[INFO]`))
				: (this.info = () => {}),
			this.levelInfo >= q.warn && this.isDebugModeEnabled
				? (this.warn = console.log.bind(console, `[WARN]`))
				: (this.warn = () => {}),
			this.levelInfo >= q.error && this.isDebugModeEnabled
				? (this.error = console.log.bind(console, `[ERROR]`))
				: (this.error = () => {})
	}
```

So the problem was functional functions just got converted into `void 0`. After return the correct function for it, the logger worked again. But the plugin still didn't work. There are many `void 0` instances in my `main.js` and I suspect that the reason was functional functions get turned into `void 0` and it didn't function the way it should be.

If anyone would send the "functional" `main.js`, I can try to investigate and see what's the difference.

@RafaelGB, I never have any experience with how all the code get compressed into a single `main.js` file. It would be great if you could give me some keywords for me to investigate further. Thanks!

This is my [`main.js`](https://drive.google.com/file/d/1Un3TJ0G5TOscXL9aquivrXMsJZYr6dwH/view?usp=sharing) (already formatted) in case anyone's interested.
